### ISSUE TITLE
Wrong when object not detected

### ISSUE THREAD

**Issue by Zames-Chang** [chonyy/AI-basketball-analysis#5]
若 input 給的是不相關的圖片，會導致找不到物件位子直接抱錯，應用 try and expect 處理。

**Comment by chonyy** [comment]
That absolutely should not happen. 
Thank you for finding out the problem.
I will work on it and apply some exception handling ASAP.
Once again, good to know you :)

**Comment by chonyy** [comment]
Hi, this problem is fixed. Please feel free to double-check it.
