### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by Xanthorapedia** [chonyy/AI-basketball-analysis#8]
I wonder if you will be publishing your dataset for detection. Thanks. Impressive work by the way!

**Comment by chonyy** [comment]
Thanks for liking it. 
As for the dataset, I will consider it. The main concern is that that dataset is basically a bunch of photos of me shooting basketball, which means a lot of my stupid faces are included. That's kind of a big problem...

**Comment by Xanthorapedia** [comment]
I see. Very reasonable concern. I personally wouldn't do that either.
However, can you describe your workflow for collecting the dataset?

**Comment by chonyy** [comment]
It's actually really simple. I used my phone to took about 500 photos on the court, and manually labeled them all.

**Comment by Crescentz** [comment]
> It's actually really simple. I used my phone to took about 500 photos on the court, and manually labeled them all.
Could you give me an example of your data, just a few pieces and how to make labels  ?Photos can be blurred
